### ISSUE TITLE
Create a new release

### ISSUE THREAD

**Issue by krille-chan** [kdy1/flutter_open_notification_settings#2]
Hey there :) thanks for merging my pull request. Currently I'm importing your package using the git-url. Could you create a new release on pub.dev to make this a little bit smoother?

Thank you very much.
Best regards and stay healthy

**Comment by kdy1** [comment]
Oh.. I thought I published it. I'll do it now.

**Comment by kdy1** [comment]
Did it. It was blocked by LICNSE file being placeholder

**Comment by krille-chan** [comment]
Thank you very much 😊
